hostname = gs-loc.apple.com, gs-loc-cn.apple.com

^https://gs-loc\.apple\.com/clls/wloc url script-response-body https://raw.githubusercontent.com/SaulGoodCode/ios-position/main/quantumultx/fake_wloc.js
^https://gs-loc-cn\.apple\.com/clls/wloc url script-response-body https://raw.githubusercontent.com/SaulGoodCode/ios-position/main/quantumultx/fake_wloc.js
